### ISSUE TITLE
Document JavaScript code on the HTML page(s)

### ISSUE THREAD

**Issue by shrey183** [shrey183/Symbolic-Calculator#11]
Follow the standard suggested on the following page: 
https://milmazz.uno/article/2014/08/27/how-to-document-your-javascript-code/

There are multiple html pages, so you could work on one or multiple pages.

**Comment by mattk410** [comment]
Hi @shrey183,
In addition to documenting the JS code, how would you feel about separating it into .js files to separate it from the HTML? It is considered good practice to stick to one language per file whenever possible.
